const sentences = [
  'افكارك الكروكي …. هحولها لتصميمات تجنن',
  'Bees can fly up to 5 miles just to find food.',
  'Old posts reborn like new… just send me the image',
  'اعرف منافسينك بيعملو ايه وانت مكانك',
  'تحب تصميم معايدة؟ رمضان على الابواب',
  'ايوة …. انا بس اللي بعرف اكتب عربي صح على الصور!',
  'Here is a bio that sounds cooler than your old one',
  'C’mon, I’m not CHEAP!!!!! I’m budget friendly',
  'افكار بودكاست ايها علاقة بيك و مسلية فعلا',
  'Voiceover scripts that sound human, not robotic',
  'متهيألي المقاس اللي قولتة مش مضبوط! الصح ١:١',
  'Captions that make people stop scrolling',
  'عايز صور لمنتجك تستعملها على الموقع؟ سيبها عليا؟',
  'Ads that don’t feel like ads, that punch',
  'بص التصميم حلو… بس لو تحب اقدر احسنة اكتر',
  'Just say it and I will turn this design into a world-class video',
  'The buzzing sound comes from bees beating their wings 200 times per second.',
  'Of course I can write mails and send them to whoever',
  'خلينا نضيف الحجاب للتصميم، يدي إحساس مصري أكتر. تحب نبدأ؟',
  'Need Logo animation to use in your branding?',
  'Hold my coffee while I create that game-changing visual',
  'مبروك المشروع الجديد … تحب نبتدي بالموقع؟',
  'A whole month’s content plan… done !',
  'All of your social posts in a snap',
  'Show me the design you like and I’ll show you what I can do',
  'Content for LinkedIn? What about a free image from VIZZY!',
  'اتفضل خطة تسويقية كاملة، تحب نبتدي بالتصميمات؟',
  'Ok, upload your  your logo and let’s make it yours all the way!',
  'Actually, I’ll finish both directions for you before you call the client',
  'Endless UGC actors talking about your brand',
  'Campaign ideas that don’t feel recycled',
  'Did you try VIBE marketing? I guess it’s time',
  'Yeah sure, I can generate 10 new ideas for this post and let’s pick the best we like',
  'Product descriptions people read and believe',
  'البادجات كدة غلط…. تسمحلي اعيد توزيعها؟',
  'Even if it’s a minor edit—let’s do it together',
  'Emails your audience actually want to open',
  'عايز تعمل فيديو لمنتجك؟ صوره وابعتهولي',
  'Show me the design you like and I’ll show you what I can do',
  'No need to hire a copywriter… we are not in 2024 anymore!',
  'Yeah I know all of the latest trends, let me pick what suits our brand',
  'لو مش عايز تكتب ابعت فويس وانا حفهم قصدك',
];

export default sentences;