// vizzy-frontend/src/constants/subscriptions.ts

/**
 * Subscription Type IDs from Django Database
 * Generated by: python manage.py get_subscription_ids
 */

export const SUBSCRIPTION_IDS = {
  PRO: '4797626d-c728-42a5-a9e3-3e5e0f3a074a',
  GROW: '2055eb44-23f1-4cce-b5dc-da0af3ebb653',
  UNLIMITED: 'e83c7d35-5d87-4798-a227-d58d5b9c3946',
} as const;

export type SubscriptionTypeId = typeof SUBSCRIPTION_IDS[keyof typeof SUBSCRIPTION_IDS];
