# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - vizzzyWebApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install and build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_SUPABASE_SERVICE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_SERVICE_KEY }}
        run: |
          npm ci
          npm run build

      - name: Create deployment package
        run: |
          echo "Creating deployment package..."
          mkdir -p deployment
          
          echo "Copying .next folder..."
          cp -r .next deployment/.next
          
          echo "Copying node_modules..."
          cp -r node_modules deployment/node_modules
          
          echo "Copying public folder..."
          cp -r public deployment/public
          
          echo "Copying src folder (for middleware)..."
          cp -r src deployment/src 2>/dev/null || echo "No src folder found"
          
          echo "Copying package files..."
          cp package.json deployment/package.json
          cp package-lock.json deployment/package-lock.json
          
          echo "Copying next.config files..."
          cp next.config.* deployment/ 2>/dev/null || true
          
          echo "Copying tsconfig.json..."
          cp tsconfig.json deployment/ 2>/dev/null || true
          
          echo "Verifying .next folder..."
          ls -la deployment/.next/
          echo "Verifying .next/server folder..."
          ls -la deployment/.next/server/ || echo "No server folder found"
          echo "Verifying .next/server/app folder..."
          ls -la deployment/.next/server/app/ || echo "No app folder found"
          
          echo "Creating release.zip..."
          cd deployment
          zip -r ../release.zip .
          cd ..
          
          echo "Deployment package created successfully"
          ls -lh release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Unzip deployment package
        run: |
          echo "Unzipping release.zip..."
          unzip -q release.zip -d deployment
          
          echo "Verifying deployment contents..."
          ls -la deployment/
          
          echo "Verifying .next folder in deployment..."
          ls -la deployment/.next/ || echo ".next folder not found!"
          
          echo "Verifying .next/server folder..."
          ls -la deployment/.next/server/ || echo "server folder not found!"
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_60CD296CA9544952A2889AC6F6DF1C24 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_31FD7D403C2D4B368D7609E371CC7AA5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_908A8BEBFD224116AB5FC8808EEAE4EA }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vizzzyWebApp'
          slot-name: 'Production'
          package: deployment